#!/usr/bin/ruby

in_contents = File.read("#{ARGV[0]}")
out_contents = File.read("#{ARGV[1]}")
eta_contents = File.read("#{ARGV[2]}")

if out_contents.include? "NONE"
  exit 0 if eta_contents.include? "NONE"
  exit 5
end

exit 5 if eta_contents.include? "NONE"

in_numbers = in_contents.chomp.split(' ').map{ |o| o.to_i }
out_numbers = out_contents.chomp.split(' ').map{ |o| o.to_i }
eta_numbers = eta_contents.chomp.split(' ').map{ |o| o.to_i }

exit 4 if eta_numbers.length != out_numbers.length

exit 5 if out_numbers[0] * in_numbers[0] + out_numbers[1] * in_numbers[1] != in_numbers[2]

exit 0
